add two cases - self-service GIS
kadaster/labs.kadaster.nl pull request #46
Opened 2020-09-30 13:33 UTC by lexirowland

2020-10-01 08:30 UTC, Roprop requested changes
Few minor remarks. If you address these we can add them to the master.

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +# Gebruiksgeval: Self Service GIS - Een Visioen
Use case needs no translation to 'gebruiksgeval' (we use the term often on our website)

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +# Gebruiksgeval: Self Service GIS - Een Visioen
Vision is better translated to 'visie' 

Een 'visoen' refers to a supernatural phenomenon in which you see ghosts, as in a Scrooge (from the Christmas Carol) type of dream in which ghosts show you the way.  

Even better, make it 'our vison' (Een visie)

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +## Zelfbediening GIS gedefinieerd
I would suggest to keep Self-Service GIS un-translated, for consistency.

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +## Introductie
Probably best to start off the page (first line) with a reference to the English page, now that we have it.

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +Esri, de toonaangevende commerciële leverancier van geospatiale software en clouddiensten voor geo-informatie, definieert self-service GIS als een uitbreiding op de typische functionaliteit die binne
Does Esri have the only definition of Self-Service GIS? Or might we have our own views about it?

(Genuine question)

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> + - Data Browsers en Viewers
Probably nicer to make these parts part of the header (using ###

i.e. 
### Data Browsers en Viewers

and 

### Analytics Dashboards

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_eng.md
> +# Use Case: Self Service GIS - A Vision
See comments to the dutch page.

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +## Self-Service GIS Architecture
Are these parts you intend to fill in later? Otherwise, it might be good to comment them out (they distract from the page if they are not filled in or at the very least joined with a **work in progress* note.

2020-10-01 08:30 UTC, Roprop commented on cases/selfservice_dutch.md
> +## Introductie
Also, be aware that the page can now only be reached through the exact link labs.kadaster.nl/cases/self-service_dutch and not through the index at labs.kadaster.nl/cases

2020-10-14 10:17 UTC, lexirowland commented on cases/selfservice_dutch.md
> +## Introductie
I am not quite sure how to do this. Can you give me some guidance?

2020-10-14 10:19 UTC, lexirowland commented on cases/selfservice_dutch.md
> +Esri, de toonaangevende commerciële leverancier van geospatiale software en clouddiensten voor geo-informatie, definieert self-service GIS als een uitbreiding op de typische functionaliteit die binne
No, we (I) have our own views on it. It is a more extended and philosophical view of it - paper upcoming!

2020-10-15 15:09 UTC, merged